import { NextResponse } from "next/server";
import ExcelJS from "exceljs";
import { prisma } from "@/lib/prisma";

export async function GET() {
    const transaksi = await prisma.transaksis.findMany({
        orderBy: {
            transactionDate: "desc",
        },
    });

    const workbook = new ExcelJS.Workbook();
    const worksheet = workbook.addWorksheet("Data Transaksi");

    // ===== KOP LAPORAN =====

    worksheet.mergeCells("A1:N1");
    worksheet.getCell("A1").value = "ROSIN APPAREL";
    worksheet.getCell("A1").font = {
        bold: true,
        size: 18,
    };
    worksheet.getCell("A1").alignment = {
        horizontal: "center",
    };

    worksheet.mergeCells("A2:N2");
    worksheet.getCell("A2").value =
        "Dashboard Analisis Penjualan dan Customer E-Commerce";
    worksheet.getCell("A2").font = {
        size: 14,
        bold: true,
    };
    worksheet.getCell("A2").alignment = {
        horizontal: "center",
    };

    worksheet.mergeCells("A4:N4");
    worksheet.getCell("A4").value = "LAPORAN DATA TRANSAKSI";
    worksheet.getCell("A4").font = {
        size: 14,
        bold: true,
    };
    worksheet.getCell("A4").alignment = {
        horizontal: "center",
    };

    worksheet.getCell("A6").value = "Tanggal Export";
    worksheet.getCell("B6").value = new Date().toLocaleString("id-ID");

    worksheet.getCell("A7").value = "Total Data";
    worksheet.getCell("B7").value = transaksi.length;

    // ===== HEADER TABEL =====

    const headerRow = 9;

    worksheet.columns = [
        { header: "No", key: "no", width: 10 },
        { header: "Customer ID", key: "customerId", width: 20 },
        { header: "Transaction Date", key: "transactionDate", width: 20 },
        { header: "Product Category", key: "productCategory", width: 25 },
        { header: "Unit Price", key: "unitPrice", width: 20 },
        { header: "Quantity", key: "quantity", width: 15 },
        { header: "Total Amount", key: "totalAmount", width: 20 },
        { header: "Discount Amount", key: "discountAmount", width: 20 },
        { header: "Payment Method", key: "paymentMethod", width: 20 },
        { header: "Device Type", key: "deviceType", width: 20 },
        { header: "Session Duration", key: "sessionDuration", width: 20 },
        { header: "Pages Viewed", key: "pagesViewed", width: 15 },
        { header: "Returning Customer", key: "returningCustomer", width: 20 },
        { header: "Customer Rating", key: "customerRating", width: 20 },
    ];

    const header = worksheet.getRow(headerRow);

    header.values = [
        "No",
        "Customer ID",
        "Transaction Date",
        "Product Category",
        "Unit Price",
        "Quantity",
        "Total Amount",
        "Discount Amount",
        "Payment Method",
        "Device Type",
        "Session Duration",
        "Pages Viewed",
        "Returning Customer",
        "Customer Rating",
    ];

    header.eachCell((cell) => {
        cell.font = {
            bold: true,
            color: { argb: "FFFFFFFF" },
        };

        cell.fill = {
            type: "pattern",
            pattern: "solid",
            fgColor: { argb: "2563EB" },
        };

        cell.alignment = {
            horizontal: "center",
            vertical: "middle",
        };

        cell.border = {
            top: { style: "thin" },
            left: { style: "thin" },
            right: { style: "thin" },
            bottom: { style: "thin" },
        };
    });

    // ===== DATA =====

    transaksi.forEach((item, index) => {
        const row = worksheet.addRow([
            index + 1,
            item.customerId,
            new Date(item.transactionDate).toLocaleDateString("id-ID"),
            item.productCategory,
            item.unitPrice,
            item.quantity,
            item.totalAmount,
            item.discountAmount,
            item.paymentMethod,
            item.deviceType,
            item.sessionDurationMinutes,
            item.pagesViewed,
            item.isReturningCustomer ? "Yes" : "No",
            item.customerRating,
        ]);

        row.eachCell((cell) => {
            cell.border = {
                top: { style: "thin" },
                left: { style: "thin" },
                right: { style: "thin" },
                bottom: { style: "thin" },
            };
        });
    });

    // ===== FOOTER =====

    const footerRow = worksheet.rowCount + 3;

    worksheet.mergeCells(`A${footerRow}:N${footerRow}`);

    worksheet.getCell(`A${footerRow}`).value =
        "Generated by Dashboard Analisis Penjualan dan Customer ROSIN APPAREL";

    worksheet.getCell(`A${footerRow}`).alignment = {
        horizontal: "center",
    };

    worksheet.getCell(`A${footerRow}`).font = {
        italic: true,
    };

    // ===== FILE =====

    const buffer = await workbook.xlsx.writeBuffer();

    return new NextResponse(buffer, {
        headers: {
            "Content-Type":
                "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
            "Content-Disposition":
                `attachment; filename=Laporan_Transaksi_${new Date()
                    .toISOString()
                    .slice(0, 10)}.xlsx`,
        },
    });
}